name: PUBLISH

on:
  push:
    branches:
      - develop  # Dispara quando houver merge na develop

jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    uses: vyracare/vyracare-infra-pipes-angular/.github/workflows/cd-angular.yml@main
    with:
      branch-name: ${{ github.ref_name }}
      codeartifact-domain: vyracare-design-system
      codeartifact-repo: vyracare-design-system
      codeartifact-domain-owner: '510253726006'
    secrets: inherit
